[tool.poetry]
name = "django-payments-sepa"
version = "1.0.1"
packages = [
    { include = "djp_sepa" }
]
description = "django-payments provider for SEPA"
authors = ["Dominik George <dominik.george@teckids.org>"]
license = "Apache-2.0"
repository = "https://edugit.org/AlekSIS/libs/django-payments-sepa"

[tool.poetry.dependencies]
python = "^3.9"
django-payments = "^0.15.0"
django-localflavor = "^3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
