[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"


[project]
name = "proxycalc"
authors = [{name = "Ebube Okoli", email = "ebubeokoli@rocketmail.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
readme = "README.md"
requires-python = ">=3.7"

[project.urls]
Home = "https://github.com/leonardokhorliey/proxycalc"


