[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry]
authors = ["Denis Rosset <physics@denisrosset.com>"]
description = "Configuration from command line parameters, configuration files and environment variables"
license = "MIT"
name = "configpile"
readme = "README.rst"
repository = "https://github.com/denisrosset/configpile.git"
version = "6.0.0"

[tool.poetry.dependencies]
class-doc = "^0.2.6"
python = "^3.8"
typing-extensions = "^4.1.1"

parsy = {version = "^1.4.0", optional = true}
rich = {version = "^11.2.0", optional = true}

[tool.poetry.extras]
parsy = ["pasry"]
rich = ["rich"]

[tool.poetry.dev-dependencies]
black = "^22.1.0"
commitizen = "^2.21.2"
isort = "^5.10.1"
mypy = "0.940"
pytest = "^7.0.1"
pytest-black = "^0.3.12"
pytest-cov = "^3.0.0"
pytest-mypy-plugins = "^1.9.3"

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
files = [
  "src/configpile",
  "tests",
]
mypy_path = "$MYPY_CONFIG_FILE_DIR/src"
no_implicit_optional = true
no_implicit_reexport = true
python_version = "3.8"
show_column_numbers = true
show_error_codes = true
show_error_context = true
show_none_errors = true
strict_equality = true
strict_optional = true
warn_redundant_casts = true
warn_return_any = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = 'parsy'

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = 'class_doc'

[tool.pytest.ini_options]
addopts = [
  "--black",
  "--tb=short",
]

# removed coverage as it interferes with debugging
# "--cov=result",  # "--cov=tests",  # "--cov-report=term",
# "--cov-report=xml",

testpaths = [
  "tests",
]

[tool.black]
line-length = 99
target_version = ['py38']

[tool.isort]
line_length = 99
profile = "black"
py_version = 38

[tool.commitizen]
annotated_tag = true
name = "cz_conventional_commits"
style = [
  ["qmark", "fg:#ff9d00 bold"],
  ["question", "bold"],
  ["answer", "fg:#ff9d00 bold"],
  ["pointer", "fg:#ff9d00 bold"],
  ["highlighted", "fg:#ff9d00 bold"],
  ["selected", "fg:#cc5454"],
  ["separator", "fg:#cc5454"],
  ["instruction", ""],
  ["text", ""],
  ["disabled", "fg:#858585 italic"],
]
tag_format = "v$major.$minor.$patch$prerelease"
update_changelog_on_bump = true
version = "6.0.0"
version_files = [
  "src/configpile/__init__.py:version",
  "pyproject.toml:version",
]
