[tool.poetry]
name = "noname-backend-common"
version = "0.1.4"
description = ""
authors = ["andre <andre@void.fyi>"]
packages = [
    { include = "noname_backend", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "*"
pysqlite3 = "*"
peewee = "*"

[tool.poetry.dev-dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
