[tool.poetry]
name = "arcane-googleads"
version = "3.4.6"
description = "Un package pour interagir avec l'API Google Ads"
readme = "README.md"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
arcane-core = "^1.5.0"
arcane-datastore = "^1.0.2"
arcane-requests = "^0.1.3"
arcane-secret = "^0.2.0"
backoff = "1.10.0"
google-ads = "^13.0.0"
python = "^3.7"
pyyaml = "5.4.1"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
