[tool.poetry]
name = "soft-files"
version = "0.2.0"
description = "A homegrown file transfer protocol."
authors = ["Kronifer <44979306+Kronifer@users.noreply.github.com>"]
license = "MIT"
packages = [
    {include = "soft"}
]

[tool.poetry.dependencies]
python = "^3.8"
PyNaCl = "^1.5.0"
loguru = "^0.6.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
taskipy = "^1.9.0"

[tool.taskipy.tasks]
format = "black ."

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
