[tool.poetry]
name = "useless_lavalink"
version = "1.4.4"
description = "A fork of Red-Lavalink for useless_bot"
license = "GPL-3.0-or-later"
authors = ["MRvillager <mrvillager.dev@gmail.com>", "tekulvw"]
maintainers = ["MRvillager <mrvillager.dev@gmail.com>"]
documentation = "https://useless-lavalink.readthedocs.io/en/stable"
homepage = "https://github.com/MRvillager/useless_lavalink"
repository = "https://github.com/MRvillager/useless_lavalink"
keywords = ["lavalink", "lavalink-client", "discord", "discord.py"]
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: aiohttp",
    "Programming Language :: Python :: 3.10",
    "Topic :: Communications :: Chat",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Internet",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Typing :: Typed",
]
packages = [
    { include = "lavalink" },
]

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = ">=3.6.0|<4"
"discord.py" = "^1.7|^2"

sphinx = {version = "^3.4.2|^4", optional = true}
sphinx-rtd-theme = {version = "^1.0", optional = true}
sphinxcontrib-trio = {version = "^1.1.2", optional = true}
typing-extensions = {version = "^4.1.1", optional = true}

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-asyncio = "*"
async_generator = "*"

[tool.poetry.extras]
docs = ["sphinx", "sphinxcontrib-trio", "sphinx-rtd-theme", "typing-extensions"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/MRvillager/useless_lavalink/issues"
